// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMhKD65jFjQWtvSk89lke7QZa6WsYXTSw',
    appId: '1:743454864200:web:216f8ee866fd863e04f97d',
    messagingSenderId: '743454864200',
    projectId: 'stylecut-reservation-app',
    authDomain: 'stylecut-reservation-app.firebaseapp.com',
    storageBucket: 'stylecut-reservation-app.firebasestorage.app',
    measurementId: 'G-8W8GJ92QEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2-hP5eBeXihdkDBoactHOOs9sr-iYc-s',
    appId: '1:743454864200:android:1b291481763e6a0504f97d',
    messagingSenderId: '743454864200',
    projectId: 'stylecut-reservation-app',
    storageBucket: 'stylecut-reservation-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAm9MfaOY4xW336g0556lcYETWNpSHpbg',
    appId: '1:743454864200:ios:7882b94ecc77acd004f97d',
    messagingSenderId: '743454864200',
    projectId: 'stylecut-reservation-app',
    storageBucket: 'stylecut-reservation-app.firebasestorage.app',
    iosBundleId: 'com.example.salonapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAm9MfaOY4xW336g0556lcYETWNpSHpbg',
    appId: '1:743454864200:ios:7882b94ecc77acd004f97d',
    messagingSenderId: '743454864200',
    projectId: 'stylecut-reservation-app',
    storageBucket: 'stylecut-reservation-app.firebasestorage.app',
    iosBundleId: 'com.example.salonapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMhKD65jFjQWtvSk89lke7QZa6WsYXTSw',
    appId: '1:743454864200:web:bfd1ab0f728cb85304f97d',
    messagingSenderId: '743454864200',
    projectId: 'stylecut-reservation-app',
    authDomain: 'stylecut-reservation-app.firebaseapp.com',
    storageBucket: 'stylecut-reservation-app.firebasestorage.app',
    measurementId: 'G-B32FV1GHPC',
  );
}
